name: CI - Build & Deploy with ArgoCD (Unsafe Hardcoded Credentials)

on:
  workflow_dispatch:
    inputs:
      image_tag:
        description: 'Docker Image Tag (e.g. 1.1)'
        required: true
        default: '1.1'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        run: echo "Iphone@29082002" | docker login -u sahilk737 --password-stdin

      - name: Build and push image to Docker Hub
        run: |
          docker build -t sahilk737/tomcat:${{ github.event.inputs.image_tag }} .
          docker push sahilk737/tomcat:${{ github.event.inputs.image_tag }}

      - name: Update deployment.yaml with new image tag
        run: |
          sed -i "s|image: sahilk737/tomcat:.*|image: sahilk737/tomcat:${{ github.event.inputs.image_tag }}|" k8s/deployment.yaml

      - name: Commit and push updated manifest
        uses: EndBug/add-and-commit@v9
        with:
          add: 'python_flask/k8s/deployment.yaml'
          message: "Update image to sahilk737/tomcat:${{ github.event.inputs.image_tag }}"
          push: true
