name: CI - Build & Push to Docker Hub

on:
  workflow_dispatch:
    inputs:
      image_tag:
        description: 'Docker image tag'
        required: true
        default: 'latest'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub (Temporary for testing)
        run: echo "Iphone@29082002" | docker login -u sahilk737 --password-stdin

      - name: Build and push image
        run: |
          docker build -t sahilk737/tomcat:${{ github.event.inputs.image_tag }} .
          docker push sahilk737/tomcat:${{ github.event.inputs.image_tag }}

      - name: Update deployment manifest with new image tag
        run: |
          sed -i "s|image:.*|image: sahilk737/tomcat:${{ github.event.inputs.image_tag }}|" k8s/deployment.yaml

      - name: Commit updated manifest
        uses: EndBug/add-and-commit@v9
        with:
          add: 'k8s/deployment.yaml'
          message: "Update image to sahilk737/tomcat:${{ github.event.inputs.image_tag }}"
